/**
 * 'bulk exports' widened this helper so importer/graph code could reuse
 * the same normalized view of a schema export. v2 exports optionally declare multiple root
 * item types, but v1 files assumed a single implicit root; the coalescing logic keeps
 * both behaviours working so older exports still import cleanly.
 */
import type { SchemaTypes } from '@datocms/cma-client';
import get from 'lodash-es/get';
import { findLinkedItemTypeIds } from '@/utils/datocms/schema';
import { isDefined } from '@/utils/isDefined';
import type { ExportDoc } from '@/utils/types';

/**
 * Normalizes an export document into easy-to-query maps, helping both import and graph builders.
 */
export class ExportSchema {
  public rootItemType: SchemaTypes.ItemType;
  public rootItemTypes: SchemaTypes.ItemType[];
  public itemTypesById: Map<string, SchemaTypes.ItemType>;
  public pluginsById: Map<string, SchemaTypes.Plugin>;
  public fieldsById: Map<string, SchemaTypes.Field>;
  public fieldsetsById: Map<string, SchemaTypes.Fieldset>;

  constructor(exportDoc: ExportDoc) {
    this.itemTypesById = this.buildItemTypesMap(exportDoc);
    this.pluginsById = this.buildPluginsMap(exportDoc);
    this.fieldsById = this.buildFieldsMap(exportDoc);
    this.fieldsetsById = this.buildFieldsetsMap(exportDoc);

    this.rootItemTypes = this.computeRootItemTypes();

    if (exportDoc.version === '1') {
      this.rootItemType = this.resolveV1Root();
    } else {
      this.rootItemType = this.resolveV2Root(exportDoc);
    }

    this.rootItemTypes = this.ensureRootCoverage(this.rootItemTypes);
    if (!this.rootItemType && this.rootItemTypes.length > 0) {
      this.rootItemType = this.rootItemTypes[0];
    }
  }

  private buildItemTypesMap(exportDoc: ExportDoc) {
    const map = new Map<string, SchemaTypes.ItemType>();
    for (const itemType of exportDoc.entities.filter(
      (e): e is SchemaTypes.ItemType => e.type === 'item_type',
    )) {
      // Normalize ID to string to avoid number/string key mismatches
      map.set(String(itemType.id), itemType);
    }
    return map;
  }

  private buildPluginsMap(exportDoc: ExportDoc) {
    const map = new Map<string, SchemaTypes.Plugin>();
    for (const plugin of exportDoc.entities.filter(
      (e): e is SchemaTypes.Plugin => e.type === 'plugin',
    )) {
      map.set(String(plugin.id), plugin);
    }
    return map;
  }

  private buildFieldsMap(exportDoc: ExportDoc) {
    const map = new Map<string, SchemaTypes.Field>();
    for (const field of exportDoc.entities.filter(
      (e): e is SchemaTypes.Field => e.type === 'field',
    )) {
      map.set(String(field.id), field);
    }
    return map;
  }

  private buildFieldsetsMap(exportDoc: ExportDoc) {
    const map = new Map<string, SchemaTypes.Fieldset>();
    for (const fieldset of exportDoc.entities.filter(
      (e): e is SchemaTypes.Fieldset => e.type === 'fieldset',
    )) {
      map.set(String(fieldset.id), fieldset);
    }
    return map;
  }

  private computeRootItemTypes() {
    // Compute roots by inspecting field link targets (no incoming edges)
    const targetItemTypeIds = new Set<string>();
    for (const field of this.fields) {
      const itemTypeId = String(field.relationships.item_type.data.id);
      for (const linkedItemTypeId of findLinkedItemTypeIds(field)) {
        if (String(linkedItemTypeId) !== itemTypeId) {
          targetItemTypeIds.add(String(linkedItemTypeId));
        }
      }
    }
    return this.itemTypes.filter(
      (itemType) => !targetItemTypeIds.has(itemType.id),
    );
  }

  private resolveV1Root(): SchemaTypes.ItemType {
    if (this.rootItemTypes.length !== 1) {
      throw new Error(
        'This export file was generated by an older version of this plugin, and it is invalid because the initial model/block model cannot be determined. Please update to the most recent version of the plugin and export your schema once more.',
      );
    }
    return this.rootItemTypes[0];
  }

  private resolveV2Root(exportDoc: ExportDoc): SchemaTypes.ItemType {
    const explicitRootId = exportDoc.rootItemTypeId;
    if (explicitRootId) {
      const resolved = this.getItemTypeById(String(explicitRootId));
      // Ensure it exists in the list, even if incoming edge analysis differs
      const alreadyInRoots = this.rootItemTypes.find(
        (it) => String(it.id) === String(explicitRootId),
      );
      if (!alreadyInRoots) {
        this.rootItemTypes = [resolved, ...this.rootItemTypes];
      }
      return resolved;
    }

    if (this.rootItemTypes.length > 0) {
      return this.rootItemTypes[0];
    }

    // Fallback: pick any item type present
    const fallback = this.itemTypes[0];
    if (!fallback) {
      throw new Error('Invalid export: missing item types');
    }
    this.rootItemTypes = [fallback];
    return fallback;
  }

  get fields() {
    return Array.from(this.fieldsById.values());
  }

  get fieldsets() {
    return Array.from(this.fieldsetsById.values());
  }

  get itemTypes() {
    return Array.from(this.itemTypesById.values());
  }

  get plugins() {
    return Array.from(this.pluginsById.values());
  }

  getItemTypeById(itemTypeId: string) {
    const itemType = this.itemTypesById.get(String(itemTypeId));

    if (!itemType) {
      throw new Error('Not existing');
    }

    return itemType;
  }

  getPluginById(pluginId: string) {
    const plugin = this.pluginsById.get(String(pluginId));

    if (!plugin) {
      throw new Error('Not existing');
    }

    return plugin;
  }

  getItemTypeFields(itemType: SchemaTypes.ItemType) {
    return (
      get(itemType, 'relationships.fields.data', []) as Array<{ id: string }>
    )
      .map((f) => String(f.id))
      .map((fid) => this.fieldsById.get(String(fid)))
      .filter(isDefined);
  }

  getItemTypeFieldsets(itemType: SchemaTypes.ItemType) {
    return (
      get(itemType, 'relationships.fieldsets.data', []) as Array<{
        id: string;
      }>
    )
      .map((fs) => String(fs.id))
      .map((fsid) => this.fieldsetsById.get(String(fsid)))
      .filter(isDefined);
  }

  private buildAdjacency() {
    const adjacency = new Map<string, Set<string>>();

    const ensureNeighbors = (id: string) => {
      const key = String(id);
      if (!adjacency.has(key)) {
        adjacency.set(key, new Set());
      }
      // Safe: we just set the key above if it was missing
      return adjacency.get(key) as Set<string>;
    };

    for (const itemType of this.itemTypes) {
      const currentId = String(itemType.id);
      const neighbors = ensureNeighbors(currentId);
      const fields = this.getItemTypeFields(itemType);

      for (const field of fields) {
        for (const rawLinkedId of findLinkedItemTypeIds(field)) {
          const linkedId = String(rawLinkedId);
          if (!this.itemTypesById.has(linkedId) || linkedId === currentId) {
            continue;
          }
          neighbors.add(linkedId);
          ensureNeighbors(linkedId).add(currentId);
        }
      }
    }

    return adjacency;
  }

  private visitFrom(
    startId: string,
    adjacency: Map<string, Set<string>>,
    visited: Set<string>,
  ) {
    const queue: string[] = [startId];
    while (queue.length > 0) {
      const current = queue.shift();
      if (current === undefined || visited.has(current)) {
        continue;
      }
      visited.add(current);
      const neighbors = adjacency.get(current);
      if (!neighbors) {
        continue;
      }
      for (const neighbor of neighbors) {
        if (!visited.has(neighbor)) {
          queue.push(neighbor);
        }
      }
    }
  }

  private ensureRootCoverage(
    initialRoots: SchemaTypes.ItemType[],
  ): SchemaTypes.ItemType[] {
    if (this.itemTypes.length === 0) {
      return [];
    }

    const adjacency = this.buildAdjacency();
    const visited = new Set<string>();
    const result: SchemaTypes.ItemType[] = [];
    const resultIds = new Set<string>();

    const addSeed = (itemType: SchemaTypes.ItemType | undefined) => {
      if (!itemType) return;
      const id = String(itemType.id);
      if (!resultIds.has(id)) {
        resultIds.add(id);
        result.push(itemType);
      }
      this.visitFrom(id, adjacency, visited);
    };

    for (const root of initialRoots) {
      addSeed(root);
    }

    if (result.length === 0) {
      const fallbackRoot =
        this.rootItemType ??
        this.itemTypesById.values().next().value ??
        undefined;
      addSeed(fallbackRoot);
    }

    for (const itemType of this.itemTypes) {
      const id = String(itemType.id);
      if (!visited.has(id)) {
        addSeed(itemType);
      }
    }

    return result;
  }
}
